// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosizeController from "./autosize_controller"
application.register("autosize", AutosizeController)

import ClearFormController from "./clear_form_controller"
application.register("clear-form", ClearFormController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import ModalpopController from "./modalpop_controller"
application.register("modalpop", ModalpopController)

import NoticeTimerController from "./notice_timer_controller"
application.register("notice-timer", NoticeTimerController)

import TwittershowController from "./twittershow_controller"
application.register("twittershow", TwittershowController)
